# .github/dependabot.yml

version: 2
updates:
  # Configuración para las dependencias de Android (Gradle/Kotlin)
  - package-ecosystem: "gradle" # Para proyectos basados en Gradle (Android)
    directory: "/" # Ruta a tu directorio raíz donde está el proyecto Android
    schedule:
      interval: "weekly" # Frecuencia de las comprobaciones: diariamente, semanalmente, mensualmente
      day: "monday" # Día de la semana para comprobar (opcional)
      time: "09:00" # Hora del día para comprobar (opcional, en formato HH:MM)
      timezone: "America/Mexico_City" # Zona horaria (ajusta según tu preferencia)
    open-pull-requests-limit: 10 # Límite de PRs abiertas a la vez
    labels:
      - "dependencias-android"
      - "android"
    # Opcional: Ignorar ciertas dependencias o versiones
    # ignore:
    #   - dependency-name: "com.example.library"
    #     versions: ["< 2.0.0", "3.x"] # Ignorar versiones específicas o rangos

  # Configuración para las dependencias de iOS (Swift Package Manager)
  - package-ecosystem: "swift" # Para Swift Package Manager
    directory: "/" # Ruta a tu directorio raíz del proyecto iOS (si es mono-repo, ajusta la ruta)
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 10
    labels:
      - "dependencias-ios"
      - "ios"

  # Opcional: Si usas CocoaPods para iOS, añade otra sección
  # - package-ecosystem: "cocoapods"
  #   directory: "/" # Ruta a tu directorio raíz del proyecto iOS
  #   schedule:
  #     interval: "weekly"
  #     day: "monday"
  #     time: "09:00"
  #     timezone: "America/Mexico_City"
  #   open-pull-requests-limit: 10
  #   labels:
  #     - "dependencias-ios"
  #     - "ios"
